"""Agregando campo 'contraseña' a la tabla 'alumnos'

Revision ID: 765695ee6139
Revises: 
Create Date: 2025-03-25 20:18:08.271839

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '765695ee6139'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accesos')
    op.drop_table('invitados')
    op.drop_table('configuracion')
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.alter_column('dni',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('nombre',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('programa_estudios',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.alter_column('estado',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True,
               comment=None,
               existing_comment='A=Activo, D=Deuda',
               existing_server_default=sa.text("''"))
        batch_op.alter_column('observaciones',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=200),
               nullable=True)
        batch_op.drop_column('contraseña')

    with op.batch_alter_table('vigilante', schema=None) as batch_op:
        batch_op.alter_column('dni',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('nombre',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vigilante', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('dni',
               existing_type=sa.String(length=50),
               type_=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contraseña', mysql.VARCHAR(length=50), nullable=True))
        batch_op.alter_column('observaciones',
               existing_type=sa.String(length=200),
               type_=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('estado',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False,
               comment='A=Activo, D=Deuda',
               existing_server_default=sa.text("''"))
        batch_op.alter_column('programa_estudios',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('dni',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=False)

    op.create_table('configuracion',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('tiempo_caducidad', mysql.INTEGER(display_width=11), server_default=sa.text('3'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('invitados',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('apellido', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('accesos',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('dni', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('fecha_hora', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('estado_acceso', mysql.ENUM('PERMITIDO', 'DENEGADO'), nullable=False),
    sa.Column('observaciones', mysql.TEXT(), nullable=True),
    sa.Column('qr_creado', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('qr_expira', mysql.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['dni'], ['alumnos.dni'], name='fk_accesos_alumnos', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
